# Generated by Django 6.0 on 2025-12-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_sensor_id', models.CharField(max_length=50)),
                ('hardware_timestamp', models.BigIntegerField()),
                ('age_years', models.IntegerField()),
                ('cpu_usage', models.IntegerField()),
                ('ram_usage', models.IntegerField()),
                ('battery_health', models.FloatField()),
                ('os', models.CharField(max_length=20)),
                ('win11_compat', models.BooleanField()),
                ('energy_sensor_id', models.CharField(max_length=50)),
                ('energy_timestamp', models.BigIntegerField()),
                ('power_watts', models.IntegerField()),
                ('active_devices', models.IntegerField()),
                ('overheating', models.IntegerField()),
                ('co2_equiv_g', models.IntegerField()),
                ('network_sensor_id', models.CharField(max_length=50)),
                ('network_timestamp', models.BigIntegerField()),
                ('network_load_mbps', models.IntegerField()),
                ('requests_per_min', models.IntegerField()),
                ('cloud_dependency_score', models.IntegerField()),
                ('eco_score', models.IntegerField()),
                ('obsolescence_score', models.IntegerField()),
                ('bigtech_dependency', models.IntegerField()),
                ('co2_savings_kg_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
