# Generated by Django 5.2.7 on 2025-12-10 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_iotdata_recommendations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The question text')),
                ('options', models.JSONField(help_text='List of 4 answer options')),
                ('correct_answer', models.IntegerField(help_text='Index of correct answer (0-3)')),
                ('reactions_correct', models.JSONField(default=list, help_text='List of reactions to show on correct answer')),
                ('reactions_wrong', models.JSONField(default=list, help_text='List of reactions to show on wrong answer')),
                ('fun_fact', models.TextField(blank=True, help_text='Fun fact displayed after answering')),
                ('order', models.IntegerField(default=0, help_text='Display order of the question')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Number of correct answers')),
                ('total_questions', models.IntegerField(help_text='Total questions answered')),
                ('percentage', models.FloatField(help_text='Score as percentage')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
